# Generated by Django 4.0.5 on 2022-06-10 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
