# Generated by Django 4.0.5 on 2022-06-27 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockItem',
        ),
    ]
